# Generated by Django 4.0.4 on 2022-04-26 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='user_image',
        ),
    ]
