# Generated by Django 4.0.4 on 2022-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0004_alter_userprofile_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='img',
            field=models.ImageField(null=True, upload_to='images/contact'),
        ),
    ]
