# Generated by Django 4.0.4 on 2022-04-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0005_contactus_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='img',
        ),
    ]
