# Generated by Django 4.0.4 on 2022-04-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='profile',
        ),
    ]
