# Generated by Django 4.0.4 on 2022-04-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0003_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
