# Generated by Django 4.0.4 on 2022-04-23 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0005_profession_alter_post_slug_alter_post_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='post_module.profession'),
        ),
    ]
