# Generated by Django 4.0.4 on 2022-04-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0006_post_description_alter_post_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/persons'),
        ),
    ]
