# Generated by Django 4.0.4 on 2022-05-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0008_postvisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.DeleteModel(
            name='PostVisit',
        ),
    ]
