# Generated by Django 4.0.4 on 2022-05-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0010_postcomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComments',
        ),
    ]
