# Generated by Django 4.0.4 on 2022-05-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0011_delete_postcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
