# Generated by Django 4.0.4 on 2022-06-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0013_postcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='user',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
