# Generated by Django 4.0.4 on 2022-10-18 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0016_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
