# Generated by Django 4.0.4 on 2022-11-12 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0018_commentpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post_module.post'),
        ),
    ]
